
name: executing Wr3c0n

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 3:00 AM UTC every day 
    - cron: '0 */6 * * *'


jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
        
 
    - name: executeing R3c0n
      env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
          go install github.com/ffuf/ffuf/v2@latest
          cargo install x8
          ls
          curl -s https://wordlists-cdn.assetnote.io/data/automated/httparchive_parameters_top_1m_2024_05_28.txt > params.wl
          curl -s https://raw.githubusercontent.com/PortSwigger/param-miner/refs/heads/master/resources/words > words.txt
          curl -s https://wordlists-cdn.assetnote.io/data/automated/httparchive_directories_1m_2024_05_28.txt > directories.txt
          curl -s https://raw.githubusercontent.com/PortSwigger/param-miner/refs/heads/master/resources/params > params2.wl
          cat words.txt | sort -u > fuzz.wl
          go build -o watchtower pkg/main/main.go
          cp watchtower ./../../
          ./watchtower --ffuf-cmds=ffuf_for_workflow.txt --x8-cmds=x8_for_workflow.txt -t 3 --discord-webhook=${{ secrets.DISCORD_TOKEN }}
          ls
          
          
    - name: Commit and push output folder
      env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add res_files/
          git commit -m "Update output folder [auto]" || echo "No changes to commit"
          
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
